language: rust

rust:
  - stable

jobs:
  include:
    - arch: amd64
      os: osx
      osx_image: xcode12
      addons:
        homebrew:
          packages:
            - protobuf
            - zeromq
      env:
        - TARGET=macos-amd64
        - OPENSSL_ROOT_DIR=$(brew --prefix openssl)
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: phoenix-$TRAVIS_TAG-$TARGET.tar.gz
        skip_cleanup: true
        on:
          repo: pashinov/phoenix
          tags: true
    - arch: amd64
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libprotobuf-dev
            - protobuf-compiler
            - libzmq3-dev
      env:
        - TARGET=linux-amd64
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: phoenix-$TRAVIS_TAG-$TARGET.tar.gz
        skip_cleanup: true
        on:
          repo: pashinov/phoenix
          tags: true
    - arch: arm64
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libprotobuf-dev
            - protobuf-compiler
            - libzmq3-dev
      env:
        - TARGET=linux-arm64
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: phoenix-$TRAVIS_TAG-$TARGET.tar.gz
        skip_cleanup: true
        on:
          repo: pashinov/phoenix
          tags: true

script:
  - cargo build --release
  - if [ -n "$TRAVIS_TAG" ]; then tar -C  target/release -czf phoenix-$TRAVIS_TAG-$TARGET.tar.gz phoenix; fi
