language: rust

rust:
  - stable

jobs:
  include:
    - arch: amd64
      os: osx
      osx_image: xcode12
      addons:
        homebrew:
          packages:
            - protobuf
            - zeromq
      env: OPENSSL_ROOT_DIR=$(brew --prefix openssl)
    - arch: amd64
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libprotobuf-dev
            - protobuf-compiler
            - libzmq3-dev
    - arch: arm64
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libprotobuf-dev
            - protobuf-compiler
            - libzmq3-dev

script:
  - cargo build --release
