language: rust

rust:
  - stable

matrix:
  include:
    - env: TARGET=x86_64-apple-darwin OPENSSL_ROOT_DIR=$(brew --prefix openssl)
      os: osx
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux

script:
  - cargo build --release
